Test IndexNow In Git hub blog

diff --git a/.github/workflows/IndexNow.yml b/.github/workflows/IndexNow.yml
--- a/.github/workflows/IndexNow.yml
+++ b/.github/workflows/IndexNow.yml
@@ -19,30 +19,40 @@ jobs:
         uses: ruby/setup-ruby@v1
         with:
           ruby-version: '3.2.2'
+
+      # 3. jq 설치
+      - name: Install jq
+        run: sudo apt-get install -y jq
       
+      # 4. Jekyll 및 Bundler 설치
       - name: Install Jekyll and Bundler
         run: gem install jekyll bundler
 
       - name: Install dependencies
         run: bundle install
       
-      # 3. Jekyll 빌드
+      # 5. Jekyll 빌드
       - name: Build the site
         run: bundle exec jekyll build
 
-      # 4. URL 목록 생성
+      # 6. URL 목록 생성
       - name: Generate URL list
         run: |
-          URL_LIST=$(cat ./_site/url-list.json | jq -r '.urlList | join(",")')
-          echo "Generated URL List: [${URL_LIST}]"
-          echo "URL_LIST=[${URL_LIST}]" >> $GITHUB_ENV
+          if [ -f "./_site/url-list.json" ]; then
+            URL_LIST=$(jq -r '.urlList | join(",")' ./_site/url-list.json)
+            echo "Generated URL List: [${URL_LIST}]"
+            echo "URL_LIST=[${URL_LIST}]" >> $GITHUB_ENV
+          else
+            echo "url-list.json not found!"
+            exit 1
+          fi
 
-      # 5. Bing 에게 IndexNow API 전송
+      # 7. Bing 에게 IndexNow API 전송
       - name: Send POST request to IndexNow API
         env:
           HOST: kj1241.github.io
           KEY: be4399e1d45940f99cd62033acdfd1f4 
-          KEY_LOCATION: https://kj1241.github.io/be4399e1d45940f99cd62033acdfd1f4.txt
+          KEY_LOCATION: https://kj1241.github.io/be4399e1d45940f99cd62033acdfd1f4.txt 
           URL_LIST: ${{ env.URL_LIST }}
         run: |
           echo "Using URL List: ${URL_LIST}"
@@ -52,7 +62,7 @@ jobs:
             "host": "'"${HOST}"'",
             "key": "'"${KEY}"'",
             "keyLocation": "'"${KEY_LOCATION}"'",
-            "urlList": ['"${URL_LIST}"']
+            "urlList": ['"${URL_LIST}']
           }')
 
           # Split the response, headers, and the HTTP status code
